name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - uses: actions/checkout@v3
    - name: Unshallow Fetch
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.0'
    - name: Login to Docker Registry
      run: |
        docker login -u=princespaghetti -p="$DOCKER_PASSWORD"
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}