name: Test with goreleaser
on:
  push:
    branchess:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - uses: actions/checkout@v3
    - name: Unshallow Fetch
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.0'
    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --skip-publish --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}